spring:
  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE

server:
  port: 41800

# dev-config
---
spring:
  config.activate.on-profile: dev
  datasource:
    username: shortln
    password: 8KdXycJ4T2rf
    url: jdbc:postgresql://localhost:35432/shortln
---
